/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

repositories {
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.1.2.build.+")
    compileOnly("com.github.hyperdefined:hyperlib:1.0.14:all")
    compileOnly("me.clip:placeholderapi:2.12.2")
    implementation(files("libs/AdvancedSeasons-API.jar"))
    implementation(files("libs/RealisticSeasons-11.8.2.jar"))
}

group = "lol.hyper"
version = "1.4.9"
description = "TimeBar"
java.sourceCompatibility = JavaVersion.VERSION_25

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}

val pluginVersion = version.toString()

tasks.processResources {
    filteringCharset = "UTF-8"

    val props = mapOf("version" to pluginVersion)
    inputs.properties(props)

    filesMatching("paper-plugin.yml") {
        expand(props)
    }
}