name: TimeBar
version: ${project.version}
main: lol.hyper.timebar.TimeBar
api-version: 1.13
author: hyperdefined
website: https://www.spigotmc.org/resources/timebar.90179/
description: See the world's time as a bossbar.
softdepend: [RealisticSeasons]
load: POSTWORLD
commands:
  timebar:
    aliases: [tb]
    usage: /timebar
    permission: timebar.command
permissions:
  timebar.commmand:
    default: true
    description: Allows the usage of /timebar.
  timebar.reload:
    default: op
    description: Allows the usage of /timebar reload.
  timebar.enable:
    default: true
    description: Allows the usage of /timebar on.
  timebar.disable:
    default: true
    description: Allows the usage of /timebar off.