name: TimeBar
version: ${project.version}
main: lol.hyper.timebar.TimeBar
api-version: 1.21
author: hyperdefined
website: https://github.com/hyperdefined/TimeBar
description: See the world's time as a bossbar.
softdepend: [Multiverse-Core, RealisticSeasons, AdvancedSeasons, PlaceholderAPI]
load: POSTWORLD
commands:
  timebar:
    aliases: [tb]
    usage: /timebar
    permission: timebar.command
permissions:
  timebar.command:
    default: true
    description: Allows the usage of /timebar.
  timebar.reload:
    default: op
    description: Allows the usage of /timebar reload.
  timebar.enable:
    default: true
    description: Allows the usage of /timebar on.
  timebar.disable:
    default: true
    description: Allows the usage of /timebar off.